"""RPC protocol implementation for NotebookLM batchexecute API."""

from .decoder import (
    AuthError,
    ClientError,
    NetworkError,
    RateLimitError,
    RPCError,
    RPCErrorCode,
    RPCTimeoutError,
    ServerError,
    UnknownRPCMethodError,
    collect_rpc_ids,
    decode_response,
    extract_rpc_result,
    get_error_message_for_code,
    parse_chunked_response,
    safe_index,
    strip_anti_xssi,
)
from .encoder import build_request_body, encode_rpc_request, nest_source_ids
from .overrides import resolve_rpc_id
from .types import (
    BATCHEXECUTE_URL,
    FLASHCARDS_VARIANT,
    INTERACTIVE_MIND_MAP_VARIANT,
    QUERY_URL,
    QUIZ_VARIANT,
    UPLOAD_URL,
    ArtifactStatus,
    ArtifactTypeCode,
    AudioFormat,
    AudioLength,
    ChatGoal,
    ChatResponseLength,
    DriveMimeType,
    ExportType,
    InfographicDetail,
    InfographicOrientation,
    InfographicStyle,
    QuizDifficulty,
    QuizQuantity,
    ReportFormat,
    RPCMethod,
    SlideDeckFormat,
    SlideDeckLength,
    VideoFormat,
    VideoStyle,
    artifact_status_to_str,
    get_batchexecute_url,
    get_query_url,
    get_upload_url,
)

__all__ = [
    "RPCMethod",
    "BATCHEXECUTE_URL",
    "QUERY_URL",
    "UPLOAD_URL",
    "get_batchexecute_url",
    "get_query_url",
    "get_upload_url",
    "resolve_rpc_id",
    "ArtifactTypeCode",
    "FLASHCARDS_VARIANT",
    "QUIZ_VARIANT",
    "INTERACTIVE_MIND_MAP_VARIANT",
    "ArtifactStatus",
    "artifact_status_to_str",
    "AudioFormat",
    "AudioLength",
    "VideoFormat",
    "VideoStyle",
    "QuizQuantity",
    "QuizDifficulty",
    "InfographicOrientation",
    "InfographicDetail",
    "InfographicStyle",
    "SlideDeckFormat",
    "SlideDeckLength",
    "ReportFormat",
    "ChatGoal",
    "ChatResponseLength",
    "DriveMimeType",
    "ExportType",
    "encode_rpc_request",
    "build_request_body",
    "nest_source_ids",
    "strip_anti_xssi",
    "parse_chunked_response",
    "extract_rpc_result",
    "collect_rpc_ids",
    "decode_response",
    "safe_index",
    # Exceptions
    "RPCError",
    "AuthError",
    "NetworkError",
    "RPCTimeoutError",
    "RateLimitError",
    "ServerError",
    "ClientError",
    "UnknownRPCMethodError",
    # Error handling utilities
    "RPCErrorCode",
    "get_error_message_for_code",
]
