export const MOBILE_VIEWPORT_MAX_WIDTH_PX = 767;
export const MOBILE_VIEWPORT_MEDIA_QUERY = `(max-width: ${MOBILE_VIEWPORT_MAX_WIDTH_PX}px)`;
export const MOBILE_APP_HEADER_HEIGHT_PX = 56;
export const MOBILE_APP_HEADER_SAFE_TOP_INSET_PX = MOBILE_APP_HEADER_HEIGHT_PX + 8;
export const MOBILE_FLOATING_CONTROLS_TOP_INSET_PX = MOBILE_APP_HEADER_HEIGHT_PX + 12;
export const MOBILE_FLOATING_CONTROLS_MESSAGE_TOP_INSET_PX = MOBILE_APP_HEADER_HEIGHT_PX + 72;

export function getMobileMessageTopInsetPx(hasFloatingControls: boolean): number {
  return hasFloatingControls ? MOBILE_FLOATING_CONTROLS_MESSAGE_TOP_INSET_PX : MOBILE_APP_HEADER_SAFE_TOP_INSET_PX;
}
